### ISSUE TITLE
Final Model Output Unit Test - Geographic - Check that coordinate names are according to a standard

### ISSUE THREAD

**Issue by kyle-messier** [Spatiotemporal-Exposures-and-Toxicology/NRT-AP-Model#47]

**Comment by sigmafelix** [comment]
Do we want to use `longitude` and `latitude` or `X`/`x` and `Y`/`y`? Since we have our standards for both geographic and projected coordinate reference systems, `longitude` and `latitude` would make some confusions. If single-letter column name is not preferred, we could add a prefix `coord_` or `coordinate_`.

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology Thank you. @eva0marques, what do you think of my opinion about `long`/`lat` vs. `X`/`Y`?

**Comment by sigmafelix** [comment]
After the discussion with Eva, we decided on using `lon` and `lat` in `stdt` objects. Strict name checking is included in data conversion functions and tests. I will close the issue.
